# Generated by Django 3.0.4 on 2020-04-22 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_auto_20200422_1305'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'permissions': [('can_write_blog', 'can_delete_blog')]},
        ),
    ]
