# Generated by Django 3.0.4 on 2020-04-28 18:49

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BlogSite', '0002_auto_20200423_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='post_date',
            field=models.DateField(default=datetime.date(2020, 4, 28)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='post_date',
            field=models.DateField(default=datetime.date(2020, 4, 28)),
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('document_1', models.FileField(upload_to='uploads/')),
                ('document_2', models.FileField(upload_to='uploads/')),
                ('document_1_name', models.CharField(max_length=20)),
                ('document_2_name', models.CharField(max_length=20)),
                ('document_1_desc', models.TextField(help_text='What is this document about?', max_length=200)),
                ('document_2_desc', models.TextField(help_text='What is this document about?', max_length=200)),
                ('upload_date', models.DateField(default=datetime.date(2020, 4, 28))),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
