# Generated by Django 3.0.4 on 2020-05-02 18:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogSite', '0006_auto_20200430_1228'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vote',
            new_name='VoteRecord',
        ),
        migrations.AddField(
            model_name='document',
            name='priority',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='blog',
            name='post_date',
            field=models.DateField(default=datetime.date(2020, 5, 2)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='post_date',
            field=models.DateField(default=datetime.date(2020, 5, 2)),
        ),
        migrations.AlterField(
            model_name='document',
            name='upload_date',
            field=models.DateField(default=datetime.date(2020, 5, 2)),
        ),
    ]
